name: Deploy GitHub Pages

on:
  push:
    branches: ["main"] # mainブランチにプッシュされた時に発火
  # 手動実行も可能にする
  workflow_dispatch:

# GitHub Pagesへのデプロイに必要な権限設定
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      # 公開するディレクトリを指定
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'projects/web'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
